# Generated by Django 3.2.5 on 2021-08-08 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_email', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name_plural': 'Customer Details',
            },
        ),
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name_plural': 'Food Category',
            },
        ),
        migrations.CreateModel(
            name='FoodDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=64)),
                ('price', models.IntegerField()),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_id', to='MainApp.foodcategory')),
            ],
            options={
                'verbose_name_plural': 'Food Details',
            },
        ),
        migrations.CreateModel(
            name='CustOrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_status', models.CharField(blank=True, max_length=64, null=True)),
                ('order_address', models.CharField(blank=True, max_length=64, null=True)),
                ('bill_amount', models.IntegerField(blank=True, null=True)),
                ('cust_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cust_id', to='MainApp.customerdetails')),
            ],
            options={
                'verbose_name_plural': 'Customer Order Status',
            },
        ),
        migrations.CreateModel(
            name='CustOrderSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_qty', models.IntegerField()),
                ('food_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_id', to='MainApp.fooddetails')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_id', to='MainApp.custorderstatus')),
            ],
            options={
                'verbose_name_plural': 'Customer Order Selection',
            },
        ),
    ]
